In [1]:
import tensorflow as tf
from tensorflow.keras.layers import Layer
from tensorflow.keras.models import Sequential


**Step 2: Define a custom layer**

Define a custom dense layer with 32 units and ReLU activation.

In [2]:
class MyCustomDenseLayer(Layer):
    def __init__(self, units=32):
        super(MyCustomDenseLayer, self).__init__()
        self.units = units

    def build(self, inpput_shape):
        self.w = self.add_weight(shape=(inpput_shape[-1], self.units),
                                 initializer='random_normal',
                                 trainable=True
                                 )
        self.b = self.add_weight(shape=(self.units,),
                                 initializer='zeros',
                                 trainable=True
                                 )
    def call(self, inputs):
        return tf.nn.relu(tf.matmul(inputs, self.w) + self.b)

**Step 3: Integrate the custom layer into a model**

Create a Keras model using the custom layer. 

In [4]:
from tensorflow.keras.layers import Softmax

# Defining the model with Softmax in the output layer

model = Sequential([
    MyCustomDenseLayer(128),
    MyCustomDenseLayer(10),     # Hidden layer with ReLU activation
    Softmax()                   # Output layer with Softmax activation for multi-class classification
])

The **Softmax** activation function is used in the output layer for multi-class classification tasks, ensuring the model outputs probabilities that sum up to 1 for each class, which aligns with categorical cross-entropy as the loss function. This adjustment ensures the model is optimized correctly for multi-class classification.


**Step 4: Compile the model**

Compile the model with the Adam optimizer and categorical cross-entropy loss. 


In [5]:
model.compile(optimizer='adam', loss='categorical_crossentropy')
print("Model summary before building")
model.summary()

# Build the model to show parameters
model.build((1000,20))
print("\nModel summary after building:")
model.summary()

Model summary before building


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ my_custom_dense_layer           │ ?                      │   0 (unbuilt) │
│ (MyCustomDenseLayer)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ my_custom_dense_layer_1         │ ?                      │   0 (unbuilt) │
│ (MyCustomDenseLayer)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ softmax (Softmax)               │ ?                      │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)


Model summary after building:


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ my_custom_dense_layer           │ (1000, 128)            │         2,688 │
│ (MyCustomDenseLayer)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ my_custom_dense_layer_1         │ (1000, 10)             │         1,290 │
│ (MyCustomDenseLayer)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ softmax (Softmax)               │ (1000, 10)             │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,978 (15.54 KB)

 Trainable params: 3,978 (15.54 KB)

 Non-trainable params: 0 (0.00 B)

**Step 5: Train the model**

Train the model on some example data. For this example, you will generate random data for training. In practice, use a real data set. 

In [8]:
import numpy as np

# Generating random data
x_train = np.random.random((1000,20))
y_train = np.random.randint(10, size=(1000,1))

# Converting labels to categorical one-hot encoding
y_train = tf.keras.utils.to_categorical(y_train, num_classes=10)
model.fit(x_train, y_train, epochs=10, batch_size=32)


Epoch 1/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 457us/step - loss: 2.3016
Epoch 2/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 379us/step - loss: 2.2995
Epoch 3/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 470us/step - loss: 2.2950
Epoch 4/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2.2985
Epoch 5/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 349us/step - loss: 2.2972
Epoch 6/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 351us/step - loss: 2.2928
Epoch 7/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 778us/step - loss: 2.2848
Epoch 8/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2.2872 
Epoch 9/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 413us/step - loss: 2.2863
Epoch 10/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 478us/step - loss: 2.2847


In [13]:
print(y_train[:5])

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


**Step 6: Evaluate the model**

Evaluate the model using test data to see its performance. 

For this example, you will generate random test data. In practice, use a real data set. 

In [17]:
# Generating random test data
x_test = np.random.random((200,20))
y_test = np.random.randint(10, size=(200,1))

# Converting labels to categorical one-hot encoding 
y_test = tf.keras.utils.to_categorical(y_test, num_classes=10)

# Evaluate the model
loss = model.evaluate(x_test, y_test)
print(f'Test loss: {loss}')

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2.31049
Test loss: 2.308669090270996


In [24]:
y_pred = model.predict(x=np.random.random((1,20)))
print(y_pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
[[0.10012044 0.0949949  0.0949949  0.10765805 0.0949949  0.0949949
  0.0949949  0.0949949  0.10046702 0.12178501]]
